### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'addError'

### ISSUE THREAD

**Issue by ravigadila** [behave/behave-django#14]
`python manage.py behave estoresx/features`

Complete log:
``` python
Feature: Register for new account and login # estoresx/features/account.feature:1
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ravi/bit/estores/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/ravi/bit/estores/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ravi/bit/estores/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ravi/bit/estores/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/ravi/bit/estores/env/local/lib/python2.7/site-packages/behave_django/management/commands/behave.py", line 92, in handle
    exit_status = behave_main(args=behave_args)
  File "/home/ravi/bit/estores/env/local/lib/python2.7/site-packages/behave/__main__.py", line 111, in main
    failed = runner.run()
  File "/home/ravi/bit/estores/env/local/lib/python2.7/site-packages/behave/runner.py", line 659, in run
    return self.run_with_paths()
  File "/home/ravi/bit/estores/env/local/lib/python2.7/site-packages/behave/runner.py", line 680, in run_with_paths
    return self.run_model()
  File "/home/ravi/bit/estores/env/local/lib/python2.7/site-packages/behave/runner.py", line 481, in run_model
    failed = feature.run(self)
  File "/home/ravi/bit/estores/env/local/lib/python2.7/site-packages/behave/model.py", line 461, in run
    failed = scenario.run(runner)
  File "/home/ravi/bit/estores/env/local/lib/python2.7/site-packages/behave/model.py", line 773, in run
    runner.run_hook('before_scenario', runner.context, self)
  File "/home/ravi/bit/estores/env/local/lib/python2.7/site-packages/behave_django/environment.py", line 62, in run_hook
    django_test_runner.before_scenario(context)
  File "/home/ravi/bit/estores/env/local/lib/python2.7/site-packages/behave_django/environment.py", line 30, in before_scenario
    context.test()
  File "/home/ravi/bit/estores/env/local/lib/python2.7/site-packages/django/test/testcases.py", line 191, in __call__
    result.addError(self, sys.exc_info())
AttributeError: 'NoneType' object has no attribute 'addError'
```
All my Behave tests are passing when i use` --use-existing-database` option above.

**Comment by bittner** [comment]
Can you give some more context?

* Operating system and version
* Which version of python 2.7 are you using?
* Django version
* behave-django version
* Please paste some of the code that might cause the issue. (Something related to "Feature: Register for new account and login" obviously)

**Comment by ravigadila** [comment]
@bittner 
Ubuntu 16.04 LTS
Python 2.7.11
Django==1.8.9
behave-django==0.3.0
splinter==0.7.3
firefox 46.0.1+build1-0ubuntu0.16.04.2

 estoresx/features/progressive/test.feature
```
Feature: simple home
  Scenario: Visit Home Page
    Given the user accesses the url "promotions:home"
    Then I see the title "EstoresCanada"
```
 estoresx/features/steps/brows_pages.py

```
@given(u'the user accesses the url "{url}"')
def the_user_accesses_the_url(context, url):
    full_url = context.get_url(url)
    context.browser.visit(full_url)
```
 estoresx/features/environment.py
```
def before_all(context):
    call_command("oscar_populate_countries")
    call_command("storesetup")
    context.browser = Browser()

```

`$ python manage.py behave estoresx/features/progressive/test.feature`

> opening browser successfully

`AttributeError: 'NoneType' object has no attribute 'addError'`

**Comment by bittner** [comment]
Thanks! Looks like pretty much the setup demoed on the [behave docs for Django](http://behave.readthedocs.io/en/latest/django.html#splinter-example), good.

For some reason the the [test case is torn down with an empty argument list](https://github.com/django/django/blob/1.8.9/django/test/testcases.py#L170) (or with an explicit `None` argument), because the value of the incoming `result` is `None` when the [exception is handled on line 191](https://github.com/django/django/blob/1.8.9/django/test/testcases.py#L191). Maybe the exception should just not occur, then why it does in `_post_teardown()`, well, [_urlconf_teardown()](https://github.com/django/django/blob/1.8.9/django/test/testcases.py#L217) really?

The whole first test case runs until the end, is this correct? -- Anything that reminds you in Django's  source code of an issue you crossed before?

It's well probable that there is some issue with you fixturer setup (the two commands you call in `before_all`), which corrupts the test database. Because the whole problem seems really like a Django TestCase issue to me; nothing strictly related to `behave-django`. -- Is there any more code you can share?

**Comment by ravigadila** [comment]
@bittner 
The whole first test case runs until the end, is this correct?
No, tests not running, just browser opened without url.

All my BDD tests successfully running with django-behave with same code and created new test database. everything worked great in django-behave and --use-existing-database for behave-django

I moved  to behave-django because of active-maintenance and it can be better configurable.

when i comment on `call_commands in before_all` for your confirmation i got below error while running tests
```
raise WebDriverException("The browser appears to have exited "
selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.

```

**Comment by bittner** [comment]
Ravi, there is a reason why your BDD tests execute successfully with `--use-existing-database`. It is because Django's test database set-up and tear-down is not executed.

If your "normal" test execution breaks because Django fails to set up and maintain the test database, there is something seriously broken with your setup. And from the information you provide there seems to be only one place where things go wrong:

``` python
call_command("oscar_populate_countries")
call_command("storesetup")
``` 

What do those two management commands do?

**Note:** `--use-existing-database` does _not_ exist to make it easy for people to live with broken test setups. This switch exists to allow you to run your tests against a local copy of your live data to _help you with the analysis of problems_ with real data, to help you gain insights beyond clean, isolated test setups. But those insights are then meant to _flow back_ into the _clean, isolated test setup_ -- and maybe a scripted database initialization, or fixtures.

Please, fix your project problems first. Not even the best-maintained project can help you if you break stuff in private code. (And Django is one of those very well-maintained projects, I would suppose. It's their code you break with some unexpected setup, as it looks like.)

If you can and want to share the code of your management commands then it may be possible for people here to help you. Otherwise I would suggest you try to remove (or comment out) one or both of the two calls above in your `behave` setup. The tests should run normally then, to start with. Then try to find out which part of your code in your management commands breaks it.

Do this first. When you've found out and fixed your issue then come back here. Thank you for your understanding.

**Comment by bittner** [comment]
I'm closing this issue due to inactivity, and because it's marked "invalid". Feel free to reopen it again or simply add more comments.
